config/routes.rb
InovareTrainingCrudSessionAjax::Application.routes.draw do
  resources :users
  
  resources :products
  get 'price', controller: 'products'

  resources :orders
  get 'item_new', controller: 'orders'
  
  resources :items, only: [:index]

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'sessions#new'

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :amount, :order_id, :price, :product_id

  belongs_to :product
  belongs_to :order

  validates :amount, presence: true, numericality: true
  validates :price,  presence: true, numericality: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :user_id, :items_attributes

  has_many :items, dependent: :destroy
  accepts_nested_attributes_for :items, allow_destroy: true

  validates :user_id, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price

  has_many :items

  validates :name,  presence: true
  validates :price, presence: true, numericality: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation

  belongs_to :order

  has_secure_password

  before_save do |user|
    user.email = email.downcase
    user.create_remember_token
  end

  validates :name, presence: true
  validates :email, presence: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :signed_in_user

  def index
    @items = Item.all
  end

  private

    def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :signed_in_user

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def edit
    @order = Order.find(params[:id])
  end

  def create
    @order = Order.new(params[:order])
    @order.user_id = current_user.id

    if @order.save
      redirect_to orders_url, notice: "Order #{@order.id} was successfully created."
    else
      render action: "new"
    end
  end

  def update
    @order = Order.find(params[:id])

    if @order.update_attributes(params[:order])
      redirect_to orders_url, notice: "Order #{@order.id} was successfully updated."
    else
      render action: "edit"
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    redirect_to orders_url
  end

  def item_new
    render partial: 'item_new'
  end

  private

    def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :signed_in_user

  def index
    @products = Product.all
  end

  def price
    @product = Product.find(params[:product_id])

    render json: @product.price
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(params[:product])

    if @product.save
      redirect_to products_url, notice: "Product #{@product.name} was successfully created."
    else
      render action: "new"
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(params[:product])
      redirect_to products_url, notice: "Product #{@product.name} was successfully updated."
    else
      render action: "edit"
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to products_url
  end

  private

    def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      render 'new', locals: { notice: 'Invalid email/password combination' }
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, except: [:new]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user 
      redirect_to users_url, notice: "User #{@user.name} created and signed in."
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to users_url, notice: "User #{@user.name} was successfully updated."
    else
      render action: "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_url
  end

  private

    def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies[:remember_token] = { value: user.remember_token, expires: 2.weeks.from_now.utc }
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token]) unless cookies[:remember_token].nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/index.html.erb
<h1>Items</h1>

<table class="table table-bordered table-striped">
  <tr>
    <th>ID</th>
    <th>Order ID</th>
    <th>Product</th>
    <th>Price</th>
    <th>Amount</th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.id %></td>
    <td><%= item.order_id %></td>
    <td>(<%= item.product_id %>) <%= Product.find(item.product_id).name %></td>
    <td><%= item.price %></td>
    <td><%= item.amount %></td>
  </tr>
<% end %>
</table>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <% if signed_in? %>
    <%= link_to "Home", users_path, :class => 'brand' %>
    <li class="divider-vertical"></li>
    <li><%= link_to "Profile", current_user %></li>
    <li><%= link_to "Edit account", edit_user_path(current_user) %></li>
	<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
    <li class="divider-vertical"></li>
    <li><%= link_to "Users", users_path %></li>
    <li><%= link_to "Orders", orders_path %></li>
    <li><%= link_to "Items", items_path %></li>
    <li><%= link_to "Products", products_path %></li>
  <% else %>
    <%= link_to "Home", root_path, :class => 'brand' %>
    <li><%= link_to "Sign in", signin_path %></li>
    <li><%= link_to "Sign up", new_user_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inovare Training Crud Session Ajax</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class="navbar navbar-fixed-top">
  <nav class="navbar-inner">
    <div class="container">
      <%= render 'layouts/navigation' %>
    </div>
  </nav>
</header>

<div class="container">
  <div class="content">
    <div class="row">
      <div class="span12">
      	<%= yield %>
	  </div>
    </div>
    <footer></footer>
  </div>
</div>

</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation" class="alert alert-error">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>
      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= link_to "Add item", item_new_path, id: "new_item_link" %>

  <div id="items">
    <%= f.fields_for :items do |ff| %>
      <%= render "item_edit", f: ff %>
    <% end %>
  </div>

  <br />

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
  var selected_products = {};
  $('.product').each(function(){
    select_tag = $(this);
    var num = select_tag.val();
    var num_item = select_tag.attr('id').split("_")[3];
    selected_products[num] = num_item;
  });
  $('#new_item_link').click(function(){
    $.ajax({
      url: $(this).attr('href'),
      dataType: "html",
      data: "counter=" + new Date().getTime(),
      success: function(html) {
        $('#items').append(html);
      }
    });
    return false;
  });
  $('#items').on('change', '.product', function(){
    var select_tag = $(this);
    var num = select_tag.val();
    var num_item = select_tag.attr('id').split("_")[3];
    for (product in selected_products) {
      if (selected_products[product] == num_item) delete selected_products[product];
    }
    if (num == 0) {
      $("#" + select_tag.attr('id').replace("_product_id", "_price")).val("");
    } else if (selected_products[num] != null && selected_products[num] != num_item) {
      alert("Product already selected.");
      $("#" + select_tag.attr('id').replace("_product_id", "_price")).val("");
      select_tag.val(0);
    } else {
      selected_products[num] = num_item;
      $.ajax({
        data: {
          product_id: num
        },
        dataType: 'json',
        success: function(json){
          $("#" + select_tag.attr('id').replace("_product_id", "_price")).val(json);
        },
        url: '<%= price_path %>'
      });
    }
  });
  $('#items').on('click', '.remove_item_new_link', function(){
    var select_tag = $(this).parents('.item').find('.product');
    if (num != 0) {
      var num = select_tag.val();
      var num_item = select_tag.attr('id').split("_")[3];
      delete selected_products[num];
    }
    $(this).parents('.item').remove();
    return false;
  });
  $('#items').on('click', '.remove_item_edit_link', function(){
    var select_tag = $(this).parents('.item').find('.product');
    if (num != 0) {
      var num = select_tag.val();
      var num_item = select_tag.attr('id').split("_")[3];
      delete selected_products[num];
    }
    $(this).parents('.item').find('.delete_item').val("true");
    $(this).parents('.item').hide();
    return false;
  });
</script>

app/views/orders/_item_edit.html.erb
<div class="item">
  <h3>
    Edit item
    <%= link_to "×", "#", class: "remove_item_edit_link" %>
  </h3>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.select :product_id, Product.all.collect { |p| [ p.name, p.id ] }, { include_blank: true }, class: 'product' %>
    <%= f.text_field :price, readonly: true %>

    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

  <%= f.hidden_field :_destroy, class: "delete_item", value: "false" %>
</div>

app/views/orders/_item_new.html.erb
<div class="item">
  <h3>
    New item
    <%= link_to "×", "#", class: "remove_item_new_link" %>
  </h3>

  <div class="field">
    <%= label_tag :product_id %>
    <%= select_tag "order[items_attributes][#{params[:counter]}][product_id]", options_for_select(Product.all.collect { |p| [ p.name, p.id ] }), class: 'product', include_blank: true %>
    <%= text_field_tag "order[items_attributes][#{params[:counter]}][price]", "", readonly: true %>

    <%= label_tag :amount %>
    <%= text_field_tag "order[items_attributes][#{params[:counter]}][amount]" %>
  </div>
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Orders</h1>

<% if !notice.nil? %>
  <p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>

<table class="table table-bordered table-striped">
  <tr>
    <th>ID</th>
    <th>User</th>
    <th>Date</th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.id %></td>
    <td>(<%= order.user_id %>) <%= User.find(order.user_id).name %></td>
    <td><%= order.created_at %></td>
    <td>
      <%= link_to 'Show', order, class: 'btn btn-small' %>
      <%= link_to 'Edit', edit_order_path(order), class: 'btn btn-small' %>
      <%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-small' %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @order.user_id %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation" class="alert alert-error">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

<% if !notice.nil? %>
  <p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>

<table class="table table-bordered table-striped">
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.price %></td>
    <td>
      <%= link_to 'Show', product, class: 'btn btn-small' %>
      <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-small' %>
      <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-small' %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-error">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password, type: "password" %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation, type: "password" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<% if !notice.nil? %>
  <p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>

<table class="table table-bordered table-striped">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Email</th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td>
      <%= link_to 'Show', user, class: 'btn btn-small' %>
      <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-small' %>
      <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-small' %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>